// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmH8qL6X8Y-d_vTRG9kPlYsy7ovwSleQM',
    appId: '1:561332731359:web:5d563d2892d814afaad86a',
    messagingSenderId: '561332731359',
    projectId: 'cmsc23-todo-app-jnadolfo',
    authDomain: 'cmsc23-todo-app-jnadolfo.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jnadolfo.appspot.com',
    measurementId: 'G-PHK04HBTN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBQMVR5J2YeYED1S-LpuQvGdst5-xY9bI',
    appId: '1:561332731359:android:7d08c46b004a2084aad86a',
    messagingSenderId: '561332731359',
    projectId: 'cmsc23-todo-app-jnadolfo',
    storageBucket: 'cmsc23-todo-app-jnadolfo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FpPSR4GjPPjgCUaRSwOn3kY6B8dqqdc',
    appId: '1:561332731359:ios:8bcf58dc42ea08f8aad86a',
    messagingSenderId: '561332731359',
    projectId: 'cmsc23-todo-app-jnadolfo',
    storageBucket: 'cmsc23-todo-app-jnadolfo.appspot.com',
    iosClientId: '561332731359-74quvd0emddlch6disqopcm5tnqfo0cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-FpPSR4GjPPjgCUaRSwOn3kY6B8dqqdc',
    appId: '1:561332731359:ios:8bcf58dc42ea08f8aad86a',
    messagingSenderId: '561332731359',
    projectId: 'cmsc23-todo-app-jnadolfo',
    storageBucket: 'cmsc23-todo-app-jnadolfo.appspot.com',
    iosClientId: '561332731359-74quvd0emddlch6disqopcm5tnqfo0cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
